### ISSUE TITLE
Card hidden

### ISSUE THREAD

**Issue by jajamoks** [LaravelDaily/LaraEventTickets-QuickAdminPanel#2]
Hi im trying to integrate stripe payment, card information payment is not showing
![image](https://user-images.githubusercontent.com/24262635/34137162-598cb592-e4a4-11e7-8469-2a926e018559.png)

**Comment by PovilasKorop** [comment]
Please check JavaScript console for errors. Have you entered your stripe credentials in env file?

**Comment by jajamoks** [comment]
Yes, i entered stripe credentials that's why "pay" button appear, i have error code here:
![image](https://user-images.githubusercontent.com/24262635/34140356-0fc9d2bc-e4b5-11e7-9587-7430e4250e17.png)

**Comment by jajamoks** [comment]
i think the problem is the "#card-element" card elements are not generated

**Comment by LaravelDaily** [comment]
@jajamoks well yes, because, as you see the error in your javascript - you cannot use LIVE credentials from Stripe without HTTPS. Use the ones from Test Mode.

**Comment by jajamoks** [comment]
@LaravelDaily  thank you, i figure it out it's not working on localhost even though I use the test credentials, I buy SSL certificate and its working fine. Big thank you and advance merry christmas to the awesome man behind @LaravelDaily
